In [68]:
import numpy as np

In [69]:
myarr = np.array([1,5])

In [70]:
type(myarr)

numpy.ndarray

In [71]:
ls = [[29,np.nan,99],[3,9,6],[8,2,33]]

In [72]:
type(np.nan)

float

In [73]:
arrls = np.array(ls)

In [74]:
type(arrls)

numpy.ndarray

In [75]:
arrls.shape

(3, 3)

In [76]:
arrls

array([[29., nan, 99.],
       [ 3.,  9.,  6.],
       [ 8.,  2., 33.]])

In [77]:
dif=np.arange(1,60,2)

In [78]:
dif

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59])

In [79]:
ls1 = list(range(1,60,2))

In [80]:
dif1 = np.arange(10)

In [81]:
dif1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
ls2 = list(range(10))

In [83]:
dif1.mean()

4.5

In [84]:
arrls.min()

nan

In [85]:
np.mean(ls)

nan

In [86]:
dif.reshape(10,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35],
       [37, 39, 41],
       [43, 45, 47],
       [49, 51, 53],
       [55, 57, 59]])

### Replace every null value with the mean of the entire array

In [87]:
samplels = [[34,67,98], [67,56, np.nan], [104,np.nan,78], [np.nan,99,12], [77,102,np.nan]]

In [88]:
samplearr = np.array(samplels)

In [89]:
samplearr

array([[ 34.,  67.,  98.],
       [ 67.,  56.,  nan],
       [104.,  nan,  78.],
       [ nan,  99.,  12.],
       [ 77., 102.,  nan]])

In [90]:
y = np.isnan(samplearr)

In [91]:
y

array([[False, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True]])

In [92]:
x = np.nanmean(samplearr) 

In [93]:
samplearr[y] = x

In [94]:
samplearr

array([[ 34.        ,  67.        ,  98.        ],
       [ 67.        ,  56.        ,  72.18181818],
       [104.        ,  72.18181818,  78.        ],
       [ 72.18181818,  99.        ,  12.        ],
       [ 77.        , 102.        ,  72.18181818]])

In [95]:
type(samplearr)

numpy.ndarray